[package]
name = "Scorpion"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5", features = ["derive"] }
font8x8 = "0.3.1"
image = "0.25.5"
kamadak-exif = "0.6.1"
minifb = "0.28.0"
